
export const ULTS = [
    {
        "Part Number": "80A809387",
        "PN with Index": "80A809387",
        "Description": "SCHUTZFOLIE",
        "Pieces / Car": "1",
        "EBR": "0%",
        "Cars / Day": "735",
        "DUNS": "822002325",
        "Supplier (text)": "3M MEXICO SA DE CV ",
        "Land": "MX",
        "Zip Code": "1210",
        "City": "CDMX",
        "LT Type / Project": "Universal",
        "LT": "563147",
        "Qty KLT/SLT per Pallet": "10",
        "QTY PN per Container": "330",
        "Containers needed considering Pzs/Car, EBR & Cars/Day": "0",
        "Gebinde": "GT60169",
        "PN per Pallet": "3300",
        "Pallet": "562015",
        "Top": "562014",
        "SubZone": "MX.02.01",
        "FTL / LTL": "LTL",
        "Pick Up Frecuency (each X day)": "0",
        "Transport (Vollgut)": "1.5",
        "Transport (Leergut)": "1.5",
        "Supplier (number)": "2",
        "Inhouse": "1.69",
        "Trailer Yard": "1",
        "WH Vollgut": "2",
        "WH Leergut": "1.5",
        "ULT": "11.19",
        "Containers Soll": "0",
        "Containers considering Gebinde Round Up": "0",
        "Gebinden (pallets + tops)": "0",
        "Total Gebinden": "0",
        "Total Containers": "0"
    },
    {
        "Part Number": "80A809388",
        "PN with Index": "80A809388",
        "Description": "SCHUTZFOLIE",
        "Pieces / Car": "1",
        "EBR": "0%",
        "Cars / Day": "735",
        "DUNS": "822002325",
        "Supplier (text)": "3M MEXICO SA DE CV",
        "Land": "MX",
        "Zip Code": "1210",
        "City": "CDMX",
        "LT Type / Project": "Universal",
        "LT": "563147",
        "Qty KLT/SLT per Pallet": "10",
        "QTY PN per Container": "330",
        "Containers needed considering Pzs/Car, EBR & Cars/Day": "0",
        "Gebinde": "GT60169",
        "PN per Pallet": "3300",
        "Pallet": "562015",
        "Top": "562014",
        "SubZone": "MX.02.01",
        "FTL / LTL": "LTL",
        "Pick Up Frecuency (each X day)": "0",
        "Transport (Vollgut)": "1.5",
        "Transport (Leergut)": "1.5",
        "Supplier (number)": "2",
        "Inhouse": "1.69",
        "Trailer Yard": "1",
        "WH Vollgut": "2",
        "WH Leergut": "1.5",
        "ULT": "11.19",
        "Containers Soll": "0",
        "Containers considering Gebinde Round Up": "0",
        "Gebinden (pallets + tops)": "0",
        "Total Gebinden": "0",
        "Total Containers": "0"
    },
    {
        "Part Number": "80A825201",
        "PN with Index": "80A825201",
        "Description": "CW-BODENVERKLEIDG.",
        "Pieces / Car": "1",
        "EBR": "100%",
        "Cars / Day": "735",
        "DUNS": "812631786",
        "Supplier (text)": "AKsys de M\u017dxico S.A. de C.V.",
        "Land": "MX",
        "Zip Code": "72990",
        "City": "Puebla",
        "LT Type / Project": "Universal",
        "LT": "566280",
        "Qty KLT/SLT per Pallet": "15",
        "QTY PN per Container": "26",
        "Containers needed considering Pzs/Car, EBR & Cars/Day": "29",
        "Gebinde": "GT60375",
        "PN per Pallet": "390",
        "Pallet": "562013",
        "Top": "562012",
        "SubZone": "MX.04.05",
        "FTL / LTL": "FTL",
        "Pick Up Frecuency (each X day)": "1",
        "Transport (Vollgut)": "0.35",
        "Transport (Leergut)": "0.35",
        "Supplier (number)": "2",
        "Inhouse": "1.5",
        "Trailer Yard": "1",
        "WH Vollgut": "2",
        "WH Leergut": "1.5",
        "ULT": "8.70",
        "Containers Soll": "253",
        "Containers considering Gebinde Round Up": "255",
        "Gebinden (pallets + tops)": "17",
        "Total Gebinden": "17",
        "Total Containers": "255"
    },
    {
        "Part Number": "80A825202A",
        "PN with Index": "80A825202A",
        "Description": "CW-BODENVERKLEIDG.",
        "Pieces / Car": "1",
        "EBR": "100%",
        "Cars / Day": "735",
        "DUNS": "812631786",
        "Supplier (text)": "AKsys de M\u017dxico S.A. de C.V.",
        "Land": "MX",
        "Zip Code": "72990",
        "City": "Puebla",
        "LT Type / Project": "Universal",
        "LT": "566280",
        "Qty KLT/SLT per Pallet": "15",
        "QTY PN per Container": "26",
        "Containers needed considering Pzs/Car, EBR & Cars/Day": "29",
        "Gebinde": "GT60375",
        "PN per Pallet": "390",
        "Pallet": "562013",
        "Top": "562012",
        "SubZone": "MX.04.05",
        "FTL / LTL": "FTL",
        "Pick Up Frecuency (each X day)": "1",
        "Transport (Vollgut)": "0.35",
        "Transport (Leergut)": "0.35",
        "Supplier (number)": "2",
        "Inhouse": "1.5",
        "Trailer Yard": "1",
        "WH Vollgut": "2",
        "WH Leergut": "1.5",
        "ULT": "8.70",
        "Containers Soll": "253",
        "Containers considering Gebinde Round Up": "255",
        "Gebinden (pallets + tops)": "17",
        "Total Gebinden": "17",
        "Total Containers": "255"
    },
    {
        "Part Number": "80A825219A",
        "PN with Index": "80A825219A",
        "Description": "UNTERBODENVERKL.",
        "Pieces / Car": "1",
        "EBR": "19%",
        "Cars / Day": "735",
        "DUNS": "816630438",
        "Supplier (text)": "A&P SOLUTIONS S.A DE C.V",
        "Land": "MX",
        "Zip Code": "72730",
        "City": "Cuautlancingo",
        "LT Type / Project": "Universal",
        "LT": "562001",
        "Qty KLT/SLT per Pallet": "1",
        "QTY PN per Container": "90",
        "Containers needed considering Pzs/Car, EBR & Cars/Day": "2",
        "Gebinde": "",
        "PN per Pallet": "90",
        "Pallet": "",
        "Top": "",
        "SubZone": "MX.04.05",
        "FTL / LTL": "FTL",
        "Pick Up Frecuency (each X day)": "1",
        "Transport (Vollgut)": "0.35",
        "Transport (Leergut)": "0.35",
        "Supplier (number)": "2",
        "Inhouse": "0.88",
        "Trailer Yard": "1",
        "WH Vollgut": "2",
        "WH Leergut": "1.5",
        "ULT": "8.08",
        "Containers Soll": "17",
        "Containers considering Gebinde Round Up": "17",
        "Gebinden (pallets + tops)": "17",
        "Total Gebinden": "17",
        "Total Containers": "17"
    },
];